services:
  db:
    image: postgres:latest
    ports:
      - "5469:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: qweasdd234

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"